### ISSUE TITLE
AreaChart implementation partially supports stacking

### ISSUE THREAD

**Issue by evenwestvang** [esbullington/react-d3#167] opened 2015-03-25 12:00 UTC
Thank you for your work on an excellent library. We're looking at using it for a project and ran into a snag with the AreaChart right away.

AreaChart has code for stacking, but the implementation isn't quite done. The example in docs works because it stores its data in an indexed array, but if you follow the example and store data in `values: [{x: 0, y:0}]` D3s stacking will just overwrite the y values and since stack has `.offset('expand')` it will just normalize the set from between zero to one while keeping the yScale leading to a single pixel height chart around the 0 line.

I'm unsure how to submit a patch for this. Do you want to keep area charts, but have a parameter for stacking and normalization? Or should this be in a separate StackedAreaChart?

I'm fixing it by calculating a new yScale after the stacking is done and fixing the `yAccessor` to always refer to `d.y` as that's what the stacking outpus whatever the original accessor was.

[edited for clarity, typos, general workday haste]

**Comment by yang-wei** [comment] 2015-04-02 15:50
Thank you for the issue. Although I'm not 100% sure the graph you are talking but does it look like this [library](https://github.com/rrag/react-stockcharts) from @rrag. 

If the code of `StackedAreaChart` isn't too different from the current `AreaChart`, I'll suggest to just add a parameter for stacking.

**Comment by esbullington** [comment] 2015-04-06 14:51
Hey thanks for the issue, and sorry for the delay.  It's been a busy past week for me at work, so my spare time has been limited.

Is there any way you could show me an example of the issue you're running into on a JSFiddle?  I'm trying to guess at what your code looks like, so a concrete example would help a lot:

http://jsfiddle.net/esbullington/jp9dkh1g/

**Comment by jsanchez034** [comment] 2015-04-12 06:08
Hey @esbullington so I was running into similar issues as @evenwestvang . Here are a few examples of the area chart issues I am running into...

Here is a chart where each series "values" is an array of objects with x and y properties...

http://jsfiddle.net/0taubm5m/

Notice no chart is rendered

Here is another example where the exact same data is used but "values" is an array of arrays with values in the first two indexes (ex. "values": [x,y])...

http://jsfiddle.net/1b3m9myt/4/

Here the area chart renders below the x-axis and this is because there is no "y" values equal to zero.  This is fixed if you at least one y value of one of the series is equal to zero, for example ...

http://jsfiddle.net/j6v2477p/1/

So definitely some strange behavior. I started messing around with the code in ...
https://github.com/esbullington/react-d3/blob/master/src/areachart/AreaChart.jsx

And made these changes ....
https://github.com/jsanchez034/react-d3/commit/4cf1b9c7371ecb7409b831f16c1740696041dfce
Which looked to have fixed my issues.

Let me know what you think of the changes I made.  Let me know if you need any clarification around any of the changes.  Also thanks for the awesome library!

**Comment by esbullington** [comment] 2015-04-13 14:34
Hi @jsanchez034 thanks for your comment and very helpful JSFiddles.  I see I've definitely made a mistake in my attempt to duplicate d3's stack svg renderer.

And your fix is close.  But the scale seems like it would be a bit off (not able to try it out myself at the moment).  We shouldn't have to sum the max of each series to get the proper domain (unless I've got the wrong mental model in my mind, it should just be the maximum, not the sum of the maximums).

Let me think about this and try to come up with a fix.  In the meanwhile, if you can think of a way to fix it while keeping the appropriate scale, or if I'm wrong and you've checked that the y scale *is* correct with your approach, please consider making a pull request.  As long as the scale is correct, I'd happily merge a fix here.

Thanks again for your help!

**Comment by jsanchez034** [comment] 2015-04-14 02:05
Hi @esbullington in the examples I show in the JSFiddles the y values between series have a large difference, so if just the maximum is used then I get a graph that looks like this...

**Using Max**
![screen shot 2015-04-13 at 9 45 19 pm](https://cloud.githubusercontent.com/assets/761087/7128968/da0782ce-e227-11e4-8e5e-c990c4165f09.png)

As you can see the tops of the spikes of the graph of the series with larger values are cut off.  But if I use the sum of the maximums I can see the tops...

**Using the sum of maximum values across series**
![screen shot 2015-04-13 at 9 45 44 pm](https://cloud.githubusercontent.com/assets/761087/7128978/0b9abed2-e228-11e4-8b68-37bd83ee8148.png)

So just to clarify, the area graph is really supposed to show the aggregate of both series across the x axis correct ?

**Comment by esbullington** [comment] 2015-04-14 10:42
OK, I feel like an idiot -- the title of the issue is stacked area charts.  Poor @evenwestvang has probably unsubscribed in disgust.  My mental model in responding was of something like a "layered" area chart, with all the series starting from the same baseline, which I was doing before.  Yes, if you're doing cumulative totals, the scale obviously needs to be summed.

I wonder if there's some way we could support both kinds?  I think this may be what the "zero" offset config on the d3 stacked function does (support a layered area chart).  I wonder if we should just create two different chart types rather than pass in a prop, this might be the clearest option.

However, multitasking clearly isn't a good idea for this topic, so I'll respond more completely later when I'm at my desk.

**Comment by esbullington** [comment] 2015-04-14 13:00
So I thought about this, and it's pretty clear that when dealing with an area chart with multiple series, the stacked area chart is more common than a layered area chart.  So I think the best thing to do would be to make the stacked area chart the default area chart type when there are multiple series present.  And then create a separate chart type for layered area charts (I'm already planning on moving each chart into its own repo, although there will still be the same `react-d3` repo available that aggregates all the different chart types).

So @jsanchez034  if you'd like to make a pull request with your code changes, that would be great.  

Otherwise, I'll do something similar.

**Comment by jsanchez034** [comment] 2015-04-14 14:31
Hey @esbullington, sounds good.  I will make the pull request tonight.

**Comment by evenwestvang** [comment] 2015-04-14 14:35
So sorry, still subscribed, but haven't been paying attention. The patch I applied for this behaviour is around these parts: https://github.com/bengler/react-d3/commit/02f0c4a1beeb17981e08fe120f1a1daec798d19e.

**Comment by esbullington** [comment] 2015-04-14 14:56
Looks like you both arrived at a similar solution.  I'll wait for jsanchez034's PR, which I *think* will cover evenwestvang's needs (please let me know if it doesn't).

Thanks to both of you for your patience and assistance -- hopefully as the project becomes more mature these kinds of situations will occur less often.

**Comment by esbullington** [comment] 2015-04-16 13:45
I'm closing this issue since #167 by @jsanchez034 should take care of the issue.  Please let us know if you have any further issues.

**Closed by esbullington** 2015-04-16 13:45 UTC
