### ISSUE TITLE
clipPath for charts

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#117] opened 2015-02-16 21:48 UTC
Looking at some of the examples `LineChart`, `ScatterChart`, `CandleStickChart` these have the `circle` or `rect` at x origin bleeding into the left of the y axis. We need to either add a 

``` xml
<defs>
        <clipPath id="rd3-clipPath">
            <rect width={chartWidth} height={chartHeight} />
        </clipPath>
 </defs>
``` 

to the SVG and apply that clip to the `g` element where the chart is drawn to avoid the bleeding.

or 

Move the y axis a little to the left so does not start at x origin

what do you think is the right solution here? I prefer clipPath.

**Comment by yang-wei** [comment] 2015-02-16 23:44
Yes that will be the right solution but currently `clipPath` is [not supported](http://facebook.github.io/react/docs/tags-and-attributes.html#svg-elements) by React. 

So the hacky solution of moving the y axis can be considered.

**Comment by esbullington** [comment] 2015-02-17 13:52
I see what you're talking about.  However, sometimes this is intended behavior. I see it in scatter and line charts in other chart libraries, including Metricgraphics, Highcharts, and nvd3 (on mouseover).  More importantly, it capture the state of the data correctly (ie, that datum/data is at the x origin). 

That said, I think people should be able to alter this behavior if they want.  There are two possible ways:

1) At the present, people can (or should be able to) change this behavior by passing in custom scales and overriding react-d3's scales, although that's not yet documented.  In this case, people can set their scale and decrease the domain minimum by n% and the previous origin will effectively be shifted to the right, thereby preventing what you're describing.  If that's not the case in any of the charts supporting multiple data series, we need to fix it.  And definitely document it.  But people should be able to pass through an `xScale` and `yScale`.

2) Also, I'd be happy to consider a PR that allowed users to translate the y axis by a specific numeric amount (negative or positive).  That would allow users to alter this behavior in the way you want, by moving the y axis like you suggested as an alternative solution.  This would have the added benefit of allowing users to position the y axis in the center of the chart, if they so wish.

But I'd prefer to avoid any kind of clip path that might cut a data point in half (plus, as pointed out by @yang-wei , it appears `clipPath` is not presently supported by React, although that should be an easy fix).

**Comment by esbullington** [comment] 2015-02-17 14:01
Oh, and another easy way to solve that problem is to remove the line altogether, and just leave the ticks.  You can do that now with CSS, and if I hadn't screwed up the `strokeWidth` property in the axes, you could do it in React.  I'll fix that as soon as I get a chance.

**Comment by rrag** [comment] 2015-02-17 14:09
it is correct that the clip path property is not supported in react, I was able to achieve it in my work by adding an inline style to the `<g>

look at candlestick in
http://react-charts-d3.s3-website-us-east-1.amazonaws.com/dist/index.html

About #2, The way I did it is have a `yAxisAt={...} orient="right"` and pass the chart width + 10 so the axis is on the right side, I could also do `yAxisAt={-10} orient="left"`to get the default behavior. 

what do you think about this approach.

**Comment by esbullington** [comment] 2015-02-19 22:48
@rrag, I'm all for passing in something like `yAxisAt`.  But here's a question: what do you think about namespacing the props we're passing in, for example:

```
var axis = {
  yAxisAt: 2
}
<Chart axis={axis} />
```

Then we can use it in the child component using es6 [rest parameter](http://ariya.ofilabs.com/2013/03/es6-and-rest-parameter.html) that I'm already using in react-d3.

We're making so many `xAxisBar` and `xAxisFoo`  that I'm concerned about API clarity.  

This would be a breaking change, so we'd need to wait until 0.4 to merge it.

What do you think?  Maybe needs an issue...

**Comment by rrag** [comment] 2015-02-19 23:03
I am thinking
```javascript
<Chart axisAt={{x: chartHeight, y: 0}} />
<Chart axisAt={{x: (chartHeight / 2), y: -2}} />
<Chart axisAt={{x: chartHeight, y: chartWidth}} />
```

and the default will be `{x: chartHeight, y: 0}`

why do you see this is as a breaking change? I am not sure I understand that.

**Comment by esbullington** [comment] 2015-02-19 23:09
I'm proposing changing all the `fooAxisBar` commands to a single `axis` command, that's an object containing all the other commands.  That's how the API of most larger chart libraries works.

But in fact, I'd probably just deprecate them, and then remove them in another version or two.  In any case, it's not like I've documented much of this yet (to my chagrin, documentation is very much a priority for me after the pure react axes are merged).

**Comment by rrag** [comment] 2015-02-20 11:44
got it. I am closing this issue now, since clipPath is not supported by react and the axisAt is coming in the future.

**Closed** 2015-02-23 10:27 UTC
